### ISSUE TITLE
CMAKE_MODULE_PATH on Ubuntu

### ISSUE THREAD

**Issue by lkdjiin** [oprypin/crsfml#13]
Just for your information:

- Ubuntu 16.04.1 LTS
- SFML 2.3.2

The path to `FindSFML.cmake` is `/usr/share/SFML/cmake/Modules/FindSFML.cmake`.

I had to add `list(APPEND CMAKE_MODULE_PATH "/usr/share/SFML/cmake/Modules")` to `CMakeLists.txt` to compile all the things.

Keep the good work :smile:

**Comment by oprypin** [comment]
It is exactly the same, `/usr/share/SFML/cmake/Modules/FindSFML.cmake`, on Arch Linux, so I thought it does not need to be specified.  
Ubuntu is probably misconfigured 😐
