### ISSUE TITLE
error on cmake . using Approach 2 

### ISSUE THREAD

**Issue by devoniandave** [oprypin/crsfml#14]
cmake --version => 2.8.12.2
sfml 2.4.2 installed in /usr/local/
 
after running
$ cmake . 

get the error: 
CMake Error: The source directory "/home/dheitzman/code/crystal/crsfml/voidcsfml" does not appear to contain CMakeLists.txt.

after this, I tried copying CMakeLists.txt.in => CMakeLists.txt, then
$ cmake .

Then I get 

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:242 (find_package):
  find_package called with invalid argument
  "@SFML_VERSION_MAJOR@.@SFML_VERSION_MINOR@"

CMake Warning at CMakeLists.txt:246 (message):
  Expecting SFML
  @SFML_VERSION_MAJOR@.@SFML_VERSION_MINOR@.@SFML_VERSION_PATCH@, found SFML
  ..

-- Configuring incomplete, errors occurred!

**Comment by refi64** [comment]
Did you use a crsfml release? AFAIK that won't work with the Git version.

**Comment by oprypin** [comment]
You did not follow the instructions correctly. Approach 2 uses pre-compiled sources, which are not part of the *master* branch which you seem to be looking at.
