### ISSUE TITLE
Error loading fonts

### ISSUE THREAD

**Issue by bararchy** [oprypin/crsfml#16]
I tried a few fonts, I keep getting the same erorr:

```bash
Warning: CrSFML was built for SFML 2.4.1, found SFML 2.4.2
Warning: CrSFML was built for SFML 2.4.1, found SFML 2.4.2
Warning: CrSFML was built for SFML 2.4.1, found SFML 2.4.2
Failed to load font "/home/unshadow/Desktop/git-projects/TestGame/assests/Digirtu.ttf" (failed to create the font face)
Font.load_from_file failed (SF::InitError)
0x5555555ddf65: from_file at /home/unshadow/Desktop/git-projects/TestGame/lib/crsfml/src/graphics/obj.cr 3682:9
0x55555558f5ef: __crystal_main at /home/unshadow/Desktop/git-projects/TestGame/src/TestGame.cr 14:1
0x55555559edd9: main at /usr/lib/crystal/main.cr 12:15
0x7ffff649b511: __libc_start_main at ??
0x55555558e70a: _start at ??
0x0: ??? at ??

```

**Comment by oprypin** [comment]
Have you tried the examples and the bundled font?

**Comment by bararchy** [comment]
@oprypin Yeha, I did now, same error.
Could this be because I `make` from the git head and not the tar ball release ?

**Comment by bararchy** [comment]
Other then fonts everything seems to be working though

**Comment by oprypin** [comment]
https://github.com/oprypin/crsfml#approach-1 is the preferred way to install but I don't see how you could've gotten mismatching versions (like in the warning) if you used this method.

Regardless, the problem must be in SFML itself, not in the wrapper, and I have no idea what it could be.
