### ISSUE TITLE
The require and files should be "crsfml", not "csmfl"

### ISSUE THREAD

**Issue by asterite** [oprypin/crsfml#2]
Because in a Projectfile to include this as a library you do:

``` crystal
deps do
  github "BlaXpirit/crsfml"
end
```

But then you do:

``` crystal
require "crsfml"
```

and it doesn't work. You have to rewrite the Projectfile like this:

``` crystal
deps do
  github "BlaXpirit/crsfml", name: "csfml"
end
```

and then do:

``` crystal
require "csfml"
```

Which is more typing and unintuitive.

You are basically not following the rules for libraries, rules that are written nowhere :blush: 

But luckily the next version of the compiler will include `crystal init` which will simplify libraries creation and set them in the right track.

**Comment by oprypin** [comment]
There would be another problem. I want to `require "crsfml/graphics"` but `crystal deps` turns it into `require "crsfml/csfml/graphics"`

**Comment by oprypin** [comment]
https://github.com/BlaXpirit/crsfml/commit/1b8c7d7909bf19fa748b00f720caebf9a1f4a81f

**Comment by asterite** [comment]
Thanks!
