### ISSUE TITLE
Option for centred text?

### ISSUE THREAD

**Issue by hanyuone** [oprypin/crsfml#21]
I'm currently making a clone of the game [Rullo](http://www.coolmath-games.com/0-rullo), and I've had to make extensive use of centred text (i.e. text that had a given coordinate, and the centre of the text block was at the coordinate).

Could you provide some way for this to happen?

**Comment by oprypin** [comment]
diagnostics example has that

**Comment by hanyuone** [comment]
Yes, I know how to centre texts through the use of `local_bounds`, but I would prefer if there was an option for centring texts automatically.

**Comment by oprypin** [comment]
CrSFML provides access to SFML's APIs. This is out of scope.
