### ISSUE TITLE
Wrong example in SF::VertexArray

### ISSUE THREAD

**Issue by ghost** [oprypin/crsfml#24]
Currently when you run this example in [SF::VertexArray](http://oprypin.github.io/crsfml/api/SF/VertexArray.html)
```Crystal
lines = SF::VertexArray.new(SF::LineStrip, 4)
lines[0] = SF::Vertex.new(SF.vector2f(10, 0))
lines[1] = SF::Vertex.new(SF.vector2f(20, 0))
lines[2] = SF::Vertex.new(SF.vector2f(30, 5))
lines[3] = SF::Vertex.new(SF.vector2f(40, 2))

window.draw(lines)
```
then it gives you this:
```Crystal
in myfile.cr:44: undefined constant SF::LineStrip (did you mean 'SF::LinesStrip')

lines = SF::VertexArray.new(SF::LineStrip, 4)
                            ^~~~~~~~~~~~~
```
So using `SF::LinesStrip` instead of `SF::LineStrip` fixes it but in [the list of primitive types](http://oprypin.github.io/crsfml/api/SF/PrimitiveType.html) it says that `LinesStrip` is deprecated and then it says you should use `LineStrip` instead. That is a bit confusing.

**Comment by oprypin** [comment]
I think you're just using an old version of SFML
