### ISSUE TITLE
Support for VertexBuffer?

### ISSUE THREAD

**Issue by bolthar** [oprypin/crsfml#26]
Since 2.5 SFML has added support for a vertexarray stored directly in graphics memory. https://www.sfml-dev.org/documentation/2.5.0/classsf_1_1VertexBuffer.php .

It would be great to have it here too. Is that a huge task? I can help :)

**Comment by oprypin** [comment]
It is supported -- automatically generated if you target SFML 2.5.
You don't see it because I haven't published pre-generated sources / docs for 2.5 yet.
Try it and let me know if it works.

**Comment by oprypin** [comment]
New release + docs
https://github.com/oprypin/crsfml/releases/tag/v2.5.0
https://oprypin.github.io/crsfml/api/SF/VertexBuffer.html

**Comment by bolthar** [comment]
Wow, nice! Thanks a lot! Works just fine!
